### ISSUE TITLE
i m facing same issue but i m adding that same extension

### ISSUE THREAD

**Issue by SundarRaj768** [andrewlock/NetEscapades.Extensions.Logging#10]
i m facing same issue but i m adding that same extension. Builder.Addfile please resolve it quickly  

public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, builder) =>
                {
                    var configuration = hostingContext.Configuration.GetSection("Logging");
                    builder.AddFile(configuration);
                })
                .UseStartup<Startup>()
                .Build();

**Comment by andrewlock** [comment]
I'm sorry, you'll have to provide more information. What is the problem?

**Comment by andrewlock** [comment]
Closing as no response. Feel free to re-open if you have any more details
