### ISSUE TITLE
Sample Application as of commit d20818f does't write to file

### ISSUE THREAD

**Issue by ManfredLange** [andrewlock/NetEscapades.Extensions.Logging#11]
Just cloned the repo, using latest commit d20818f.

Running the sample application, it turns out that no log file is written. It appears as if the default value for `BatchingLoggingProvider.IsEnabled` is always `false`. As a result `BatchingLogger.Log` will return right at the first check, i.e. line 37.

Either the default value should be `true` for `IsEnabled` -or- the sample application is missing the instructions for setting the property to `true`.

OR: Perhaps I'm overlooking something?

**Comment by ManfredLange** [comment]
One option to make it log is adding the line `opts.IsEnabled = true;` to the implementation of `Program.cs` as follows:
```
   public class Program {
      public static void Main(string[] args) {
         CreateWebHostBuilder(args).Build().Run();
      }

      public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
          WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((context, builder) => builder.AddFile(opts => {
               opts.IsEnabled = true; // <===== add this line
               context.Configuration.GetSection("FileLoggingOptions").Bind(opts);
            }))
            .UseStartup<Startup>();
   }
```

**Comment by andrewlock** [comment]
Thanks for spotting this! I think the default should be for `IsEnabled` to be `True` anyway, so I'll make a quick update that should fix this very shortly 🙂
