### ISSUE TITLE
Logging only specific messages

### ISSUE THREAD

**Issue by ceallach66** [andrewlock/NetEscapades.Extensions.Logging#12]
Hi - thanks for the utility, looks very handy. I'm new to it though, so I have what is probably a dumb question: It appears to be logging not only my messages, but all informational messages from the build as well. Is there a way to restrict the log to just the messages I specifically add? I tried changing the LogLevel to "warning" but didn't notice any changes.

Thanks,
Shawn

**Comment by andrewlock** [comment]
ASP.NET Core includes "log filtering" for this purpose. There are docs [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-filtering), but I think those are a bit tricky to understand - I'll try and write a blog post about it soon. 

Which log messages are actually written by a logger is determined by the "category" of the log message  (the namespace of the `T` in `ILogger<T>`) and the filter levels defined in _appsettings.json_ (by default).

For example, in the logging section in the sample app:

https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/master/sample/SampleApp/appsettings.json#L2-L9

I have set the default filter level for the `File` logger to be `"Information"`. That means logs from any category (namespace) that are Information, Warning, or Error level (so not Debug or Trace) will be written to the file log.

In contrast, if you look at _appsettings.development.json_, you can see the log level filters (for _all_ log providers, so file/console etc) are different for different namespaces: 

https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/master/sample/SampleApp/appsettings.Development.json#L4-L8

Changing the `System` and `Microsoft` namespaces to `Warning` here will mean the normal request log messages will not appear in _any_ loggers. Alternatively, you could combine the two, something like:

```json
 "Logging": {
    "IncludeScopes": false,
    "File": {
      "LogLevel": {
        "Default": "Information",
        "System": "Warning",
        "Microsoft": "Warning"
    }
  }
}
```

Hope that helps, like I say, I'll write a blog post explaining in more depth,, as it can be tricky to understand when you're new to it 🙂

**Comment by ceallach66** [comment]
Thanks for your fast response! I look forward to seeing that article on "log filtering" in the future. However I have added the "System" and "Microsoft" clauses to the Logging section of the AppSettings.json file, but I'm still seeing informational messages from those namespaces. I rechecked my code against the Sample App and don't see anything obvious; are there any other changes I could be missing? Thanks again - Shawn

**Comment by andrewlock** [comment]
Could you paste your _appsettings.json_ file in here?

**Comment by ceallach66** [comment]
My appsettings.json:
-----------------------
{
  "ConnectionStrings": {
    "LicenseTrackingDatabase": "XXXXXXXXXXXXXXXX"
  },
  "AppConfiguration": {
    "BasicAuthUserName": "XXXXXXXXXXX",
    "BasicAuthPassword": "XXXXXXXXXXXXXXXXXXXXXXXXx"
  },
  "Logging": {
    "IncludeScopes": false,
    "File": {
      "LogLevel": {
        "Default": "Information",
        "System": "Warning",
        "Microsoft": "Warning" 
      }
    }
  },
  "FileLoggingOptions": {
    "FileName": "app-logs-",
    "FileSizeLimit": 1048576
  },
  "AllowedHosts": "*"
}

My Program.cs:
-----------------
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((context, builder) =>
                {
                    builder.AddFile(opts =>
                    {
                        context.Configuration.GetSection("FileLoggingOptions").Bind(opts);
                    });
                })
                .UseStartup<Startup>();
    }

**Comment by andrewlock** [comment]
That all looks correct to me. I just tried copying the `"Logging"` section from your appsettings.json into the sample app and it works as I'd expect: you see all the logs in the console, but the file logger doesn't write the Microsoft/System information messages... Maybe you have some different settings in your _appsettings.development.json_ file that are overwriting them...

**Comment by ceallach66** [comment]
The appsettings above is the entire file (with some data XXXX'd out), so I don't think there are other settings getting in the way. And since it runs different config files based on the environment, I traced through the code and verified it is using this one.

Ok, I'll skim through and see if I can find anything else... Thanks.

**Comment by andrewlock** [comment]
Just FYI this isn't strictly true:

> And since it runs different config files based on the environment

It doesn't choose a single file by default, it takes the default file (_appsettings.json_) and "layers" the environment specific one on top (_appsettings.development.json_). Seeing as you've checked it out, presumably it's not the issue, but just wanted to clarify

**Comment by ceallach66** [comment]
I know at least the options are getting loaded successfully, because I changed the config file as follows:
  "FileLoggingOptions": {
    "FileName": "app-logsX-",
    "FileSizeLimit": 1048576
  },

And my log file started having "logsX" in the filename. But while I'm specifying "FileLoggingOptions" there, where is it loading the "Logging" section (which includes the File LogLevels)? I'm using an alternate config file with a custom load method, so perhaps it's trying to load from the usual config file when is looks at the "Logging" options?

**Comment by ceallach66** [comment]
I noticed this was included in the .csproj file (tags removed):

Include="..\..\src\NetEscapades.Extensions.Logging.RollingFile\NetEscapades.Extensions.Logging.RollingF

But since I pulled it down from NuGet, all I have is that reference (tags removed):

Include="NetEscapades.Extensions.Logging.RollingFile" Version="1.0.1"

Does the .csproj need to be included with our code?

**Comment by andrewlock** [comment]
No, that's not necessary, you've done the right thing. The configuration is loaded inside `WebHost.CreateDefaultBuilder()`. If you can share your whole project, I can see if I can spot what's wrong, but otherwise I'm fumbling in the dark I'm afraid.

**Comment by ceallach66** [comment]
Yes, sorry - I can't really share the whole thing due to proprietary issues, and also because we're kind of adding this after much of the project has been developed, so it's quite large and complex at this point.

But as I mentioned earlier, I know the "FileLoggingOptions" are being loaded correctly - both in debug, and by the filename change. But I'd like to know where the "Logging" options are being loaded, since this is where the LogLevels are contained. And is it using the default Configuration option - context.Configuration.GetSection() - to load this config data? Because if so, it could load the wrong configuration file since we use a different config structure for our various testing environments.

**Comment by andrewlock** [comment]
The `FileLoggingOptions` section controls this extension. The `Logging` section (which includes the LogLevels) is loaded automatically by the framework inside `WebHost.CreateDefaultBuilder()`. 

I suggest reading up a bit about how the ASP.NET Core configuration system works by combining multiple sources as that may be the source of your issues. Also, make sure you read the docs on filtering of logging messages: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-filtering

Good luck!

**Comment by ceallach66** [comment]
Yes, that was it - it was getting confused with the different configuration files. Working now - thanks for your help!

**Comment by andrewlock** [comment]
Great, glad to hear it! I'll close this issue now then 🙂
