### ISSUE TITLE
Rolling periods other than daily

### ISSUE THREAD

**Issue by RyanGrange** [andrewlock/NetEscapades.Extensions.Logging#16]
I just put in a pull request for a set of options to make rolling periods other than just daily an option.  I probably should have asked if you had any interest in such an option beforehand.  If there's concern about adding the dependency on the SmartEnum class, I can redo it using a basic enum.

**Comment by RyanGrange** [comment]
Reworked PR to not depend on SmartEnum.

**Comment by andrewlock** [comment]
I've just pushed version 2.2.0 to NuGet with your change. Thanks again!
