### ISSUE TITLE
Plans for different file formats

### ISSUE THREAD

**Issue by Delphinidae84** [andrewlock/NetEscapades.Extensions.Logging#19]
Since you have introduced, the `Extension` option, do you have any plans on supporting logs for other formats, i. e. `.csv`?

Thanks for the great work btw!

**Comment by andrewlock** [comment]
Hi, thanks!

No,  I currently have no plans to change the format - if you need more features (and even if you don't!) I strongly suggest taking a look at Serilog, as it has a much longer pedigree and [great compatibility with asp.net core](https://github.com/serilog/serilog-aspnetcore)!
