### ISSUE TITLE
ILoggingBuilder' does not contain a definition for 'AddFile'

### ISSUE THREAD

**Issue by MarkusAnthony** [andrewlock/NetEscapades.Extensions.Logging#2]
Good day,

I install the nuget package via the solution nuget package manager. I see it in the dependencies.

I added the line of code to program.cs (actually cut/pasted the paragraph in case I mis-typed something).

.Net Core 2, Web Api

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ILoggingBuilder' does not contain a definition for 'AddFile' and no extension method 'AddFile' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using directive or an assembly reference?)

-Markus

**Comment by andrewlock** [comment]
Hi, thanks for trying out the package!

I've just done a couple of tests, and I can't recreate the issue you're describing. Have you tried adding the package to a new project? It sounds like the NuGet package hasn't been restored correctly for some reason, but I can't recreate the issue I'm afraid

**Comment by Delphinidae84** [comment]
@andrewlock Did the installation via `dotnet add package NetEscapades.Extensions.Logging.RollingFile`

Same issue as @MarkusAnthony 

> 'ILoggingBuilder' does not contain a definition for 'AddFile' and no extension method 'AddFile' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by Delphinidae84** [comment]
@MarkusAnthony @andrewlock 
Well in my case the problem was that neither VSCode nor Visual Studio suggested an import. Manually adding `using Microsoft.Extensions.Logging;` to `Program.cs` did solve the issue though :sweat_smile:

**Comment by andrewlock** [comment]
Closing this as no further comments. Feel free to reopen if you're still facing issues

**Comment by Fatih-Ceylan** [comment]
> @MarkusAnthony @andrewlock
> Well in my case the problem was that neither VSCode nor Visual Studio suggested an import. Manually adding `using Microsoft.Extensions.Logging;` to `Program.cs` did solve the issue though 😅

i've had same problem. work around 1 hour to solve it but that easy step fixed mine as well :)

**Comment by k1ritshah** [comment]
following package needs to install.
NuGet\Install-Package Serilog.Extensions.Logging.File -Version 3.0.0
