### ISSUE TITLE
Reading settings for options from appsettings.json

### ISSUE THREAD

**Issue by vnellore** [andrewlock/NetEscapades.Extensions.Logging#3]
Hello,

Thanks for creating this library. I am wondering what is the best way to set the various options for logging e.g., file name, log directory, file size limit etc using values from appsettings.json? I am not able to read the values in ConfigureLogging.

Thanks!
Vamsi

**Comment by andrewlock** [comment]
Hi, I've just updated the sample app to show how you could do this. You can add a section to your appsettings.json file as shown here: https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/cbfd6a2a2fc35e0976dd0591b99673b3a91dc976/sample/SampleApp/appsettings.json#L10-L13

And bind it to the file logger configuration options in _program.cs_: 
https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/cbfd6a2a2fc35e0976dd0591b99673b3a91dc976/sample/SampleApp/Program.cs#L23-L29

Hope that helps!

**Comment by vnellore** [comment]
Thank you very much for your response. This works for me.
