### ISSUE TITLE
What is the idea for not change fileName by config?

### ISSUE THREAD

**Issue by mevgdev** [andrewlock/NetEscapades.Extensions.Logging#35]
What is the problem if I use a custom file Name? , ex:
options.FileName = "diagnostics-hello-test.log";

output file:
diagnostics-hello-test.log

Why is necessary add mandatory the date at the end of name by system?

current version
output:
diagnostics-hello-test.log.20230928.txt

**Comment by andrewlock** [comment]
This is just the design of the library - it's a _rolling_ file mechanism, so it rolls the files based on the specified periodicity. If you don't want rolling files, then this library isn't for you 🙂
