### ISSUE TITLE
Configure severity of written logs

### ISSUE THREAD

**Issue by Delphinidae84** [andrewlock/NetEscapades.Extensions.Logging#4]
Is there a way to let's say do something like:

```csharp
    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging(builder => builder.AddFile(options => {
                options.FileName = "diagnostics-";
                options.LogDirectory = "LogFiles";
                options.FileSizeLimit = 20 * 1024 * 1024; 
                options.Severity = ["Warning", "Error"]; // <-- This would only log Warnings and Errors
            })) 
            .UseStartup<Startup>()
            .Build();
```

At least in my case it would be great if you could configure the severity of logging entries if it is not possible already.

**Comment by andrewlock** [comment]
Hi, you can achieve this already using the built-in log filtering. Check out [the docs here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#log-filtering) 

To achieve something like you're after, you should be able to add the `"File"` section to your _appsettings.json_

```json
{
  "Logging": {
    "File": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "LogLevel": {
      "Default": "Debug"
    }
  }
}
```

**Comment by andrewlock** [comment]
I've just updated the sample app to demonstrate this (limiting to `"Warning"` when running in production) 

https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/cbfd6a2a2fc35e0976dd0591b99673b3a91dc976/sample/SampleApp/appsettings.json#L4-L8

**Comment by andrewlock** [comment]
I'll assume this solved your problem @Delphinidae84 - if not, feel free to reopen the issue 🙂
