### ISSUE TITLE
Logging `ILogger` info to file

### ISSUE THREAD

**Issue by Delphinidae84** [andrewlock/NetEscapades.Extensions.Logging#7]
Hi,

I configured everything as described in `README.md` and it does work all (ASP.NET) logging is written to the target file as expected.

What I do not understand is how to combine `ILogger` with this extension. e. g. I have a (SignalR) Hub where I would like to write some information to log files manually:

```
    public class ConnectionHub : Hub<IConnectionClient>
    {

        private readonly ILogger<ConnectionHub> logger;

        public ConnectionHub( ILogger<ConnectionHub> logger )
        {
            this.logger = logger;
        }

        public override async Task OnConnectedAsync()
        {
            await Groups.AddToGroupAsync( Context.ConnectionId, "Clients" );
            logger.LogInformation( "{0}  Client connected - Id: {1}", DateTime.UtcNow, Context.ConnectionId );
            await base.OnConnectedAsync();
        }

        public override async Task OnDisconnectedAsync( Exception exception )
        {
            await Groups.RemoveFromGroupAsync( Context.ConnectionId, "Clients" );
            logger.LogInformation( "{0} Client disconnected - Id: {1}", DateTime.UtcNow, Context.ConnectionId );
            await base.OnDisconnectedAsync( exception );
        }
    }
```

As you can see I am using `logger.LogInformation( "{0} Client disconnected - Id: {1}", DateTime.UtcNow, Context.ConnectionId );`. The output is written to console as expected. I would have expected it to be written to the log files too, though. Did I miss something or have I not completely understood the concept?

**Comment by andrewlock** [comment]
Hi, yes if your other logs are being written to the file, and you're also seeing this log in the console, I would expect for you to see it in the file.

Remember that the file logger does batching of the logs for performance reason, so you might not see it immediately, but I wouldn't expect it to take long. 

Also, bear in mind that you can have different filter levels applied to different loggers and different namespaces. [See the docs for details.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#log-filtering). It could be that you're only logging e.g. Warning and above for messages in the ConnectionHub  namespace for the file logger (or by default)?

**Comment by Delphinidae84** [comment]
I'm sorry for the disturbance, I actually did set the wrong log level in my application settings.
