### ISSUE TITLE
There's no need to use async methods inside a dedicated thread

### ISSUE THREAD

**Issue by ghost** [andrewlock/NetEscapades.Extensions.Logging#8]
If there will be a real asynchronous operation, then its continuation will be on a thread pool thread. After that it won't return to the dedicated thread and can potentially use one threadpool thread for the rest of application lifetime.

**Comment by andrewlock** [comment]
Interesting, thanks. This article looks to describe the very same issue: http://blog.i3arnon.com/2015/07/02/task-run-long-running/

Seems like the suggestion is to change 

https://github.com/andrewlock/NetEscapades.Extensions.Logging/blob/master/src/NetEscapades.Extensions.Logging.RollingFile/Internal/BatchingLoggerProvider.cs#L102-L105

```
_outputTask = Task.Factory.StartNew<Task>(
    ProcessLogQueue,
    null,
    TaskCreationOptions.LongRunning);
```
to 
```
_outputTask = Task.Run(ProcessLogQueue);
```

Given this code is [originally taken from the ASP.NET Core framework](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLoggerProvider.cs#L133-L136), and in Azure, it's prob a good idea to raise the issue there too! 🙂

**Comment by ghost** [comment]
yes, opened it
https://github.com/aspnet/Logging/issues/941

**Comment by BBGONE** [comment]
By the way i fixed it yesterday in my copy (i removed all async methods)

https://github.com/BBGONE/JRIApp.Core/blob/master/DEMOS/RIAppDemoMVC/Extensions.Logging.RollingFile/Internal/BatchingLoggerProvider.cs

https://github.com/BBGONE/JRIApp.Core/blob/master/DEMOS/RIAppDemoMVC/Extensions.Logging.RollingFile/FileLoggerProvider.cs

**Comment by ghost** [comment]
I closed the issue there - that branch was archived
the new one is there
https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.AzureAppServices/src/BatchingLoggerProvider.cs
https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.AzureAppServices/src/FileLoggerProvider.cs

replaced the issue on the new resource
https://github.com/aspnet/Extensions/issues/571
